import { Router } from 'express';
import type { Request, Response } from 'express';
import {
  getAllAnnotations,
  calculateRelativeRect,
} from '../lib/fileStorage';
import { promises as fs } from 'fs';
import path from 'path';

const router = Router();

// Generate Python code
router.post('/generate', async (req: Request, res: Response) => {
  try {
    const annotations = await getAllAnnotations();

    // Group annotations by screenshot group
    const groupedByGroup = annotations.reduce((acc, data) => {
      const group = 'other'; // Default group, will be updated when we load screenshot metadata
      if (!acc[group]) {
        acc[group] = [];
      }
      acc[group].push(...data.currentAnnotations);
      return acc;
    }, {} as Record<string, any[]>);

    // Generate Python code
    let pythonCode = `# Auto-generated by Airtest Template Manager
# Generated at: ${new Date().toISOString()}
# Do not edit manually

from airtest.core.api import *

# Template definitions grouped by screenshot
Templates = {

`;

    // Add each template
    for (const data of annotations) {
      for (const annotation of data.currentAnnotations) {
        const relativeRect = calculateRelativeRect(
          annotation.rect,
          { width: 1920, height: 1080 } // Default resolution, should be updated
        );

        pythonCode += `  '${annotation.name}': Template(
    r'data/screenshots/${data.screenshotId}',
    record_pos=((${annotation.rect.x}, ${annotation.rect.y}, ${annotation.rect.x + annotation.rect.width}, ${annotation.rect.y + annotation.rect.height}),
    target_pos=((${relativeRect.x}, ${relativeRect.y}, ${relativeRect.x + relativeRect.width}, ${relativeRect.y + relativeRect.height}),
    resolution=(1920, 1080)
  ),

`;
      }
    }

    pythonCode += `}

print("Templates loaded successfully!")
print(f"Total templates: ${annotations.reduce((sum, data) => sum + data.currentAnnotations.length, 0)}")
`;

    // Save to output file
    const outputPath = path.join(process.cwd(), 'output', 'templates.py');
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, pythonCode);

    res.json({
      success: true,
      data: {
        message: 'Python code generated',
        path: 'output/templates.py',
        templateCount: annotations.reduce((sum, data) => sum + data.currentAnnotations.length, 0),
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, error: String(error) });
  }
});

export default router;
